# Cấu hình cơ sở dữ liệu
spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
# Cấu hình JWT
jwt:
  key: XqU4rfmKusRMK6D+d1gd9BDH71XIVmaHHadEb6wxHh4=
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

config:
  domain: http://localhost:8080
  adminId: "admin"

# Cấu hình server
server:
  port: 8080

# Cấu hình logging
logging:
  level:
    org.springframework: INFO
    com.example.server: DEBUG
